FROM literphor/basedebian:latest
MAINTAINER Literphor

LABEL Version="1.0"

RUN curl --silent --location https://deb.nodesource.com/setup_0.12 | bash -
RUN apt-get install -y nodejs
RUN apt-get install -y build-essential